### ISSUE TITLE
Support Time Scale

### ISSUE THREAD

**Issue by moberwasserlechner** [moberwasserlechner/vaadin-chartjs#15]
http://www.chartjs.org/docs/#scales-time-scale

**Comment by moberwasserlechner** [comment]
I have to include moment.js and the Data class labels must also support Dates in addition to Strings.

**Comment by dyorgio** [comment]
Hello!
What do you need to conclude this? I'm needing this feature to my application :).
Can I help you to finish the job?

**Comment by flexguse** [comment]
Is there any chance the Time Scale feature branch is merged into the main development branch? I'd really appreciate to be able to use the Time Scale.
Otherwise I would like to add this feature myself but unfortunately I don't have no experience in using Javascript from Vaadin server side so I can not guarantee for the results.

**Comment by SerVac** [comment]
Hello.
How about refresh and finish with this Time Scale future?

**Comment by marquiswang** [comment]
Would also love this. Can I help get this merged?

**Comment by moberwasserlechner** [comment]
Fix by @slatequarry in #75
