### ISSUE TITLE
[Question] Line Chart zoom in/out on mouse scrolling

### ISSUE THREAD

**Issue by alanamircruz** [moberwasserlechner/vaadin-chartjs#60]
Hey hi everybody,

My question: Is it possible to do a zoom in and out using the mouse scroll ?

If not possible do you have any suggestion in order how to implement this (or if its there one open thread about it and how to use it).

Thanks in advance for any help,
Alan

**Comment by moberwasserlechner** [comment]
Hi Alan,

I don't think this is possible right now, because also in pure ChartJs they use a plugin https://github.com/chartjs/chartjs-plugin-zoom for that.

A workaround might be difficult. Althought i should be possible to add the js-file to vaadin but as soon as you try to configure it you get stuck.

The best solution would be if I integrate the plugin directly into the addon. The addional js size shouldn't matter.

BR,
Michael

**Comment by alanamircruz** [comment]
Hey hi Michael,

Ok ok I understand, so thanks for your prompt reply and let me know if I can help with something please.

Have a nice week ahead,
Alan

**Comment by moberwasserlechner** [comment]
I will add support for it in the next release. As I want to have a typed api I will only support "String" and "Double" for the x and y value of the following options.

Let's see how this works out.
```
rangeMin: {
			// Format of min pan range depends on scale type
			x: null,
			y: null
		},
		rangeMax: {
			// Format of max pan range depends on scale type
			x: null,
			y: null
		}
```

**Comment by moberwasserlechner** [comment]
Unfortunately the zoom/pan plugin is not actively maintained so this feature might be a little experimental ;)
